platform :ios, '16.0'

def capacitor_pods
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'
end

target 'Plugin' do
  capacitor_pods
end

target 'PluginTests' do
  capacitor_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.name != "Release"
        config.build_settings['DEVELOPMENT_TEAM'] = "8XMU858E3Y"
      else
        config.build_settings['DEVELOPMENT_TEAM'] = "8XMU858E3Y"
      end
    end
  end
end
